site_name: basal_and_bark

site_url: https://ZachDorm.github.io/basal_and_bark

repo_url: https://github.com/ZachDorm/basal_and_bark

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
        #   ignore_h1_titles: True
        #   execute: True
        #   execute_ignore: "*.ipynb"
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Examples: examples/intr.ipynb
    - Examples 2: examples/folium.ipynb
    - Changelog: changelog.md
    - Report Issues: https://github.com/ZachDorm/basal_and_bark/issues
    - API Reference:
          - basal_and_bark module: basal_and_bark.md
